import Head from "next/head";
import Image from "next/image";
import styles from "../styles/About.module.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Timeline from "../components/Timeline";

export default function Home() {
  const timelineArray = [
    {
      title: "Title 1",
      description: "Desc 1",
      date: "1 March 1990",
    },
    {
      title: "Title 2",
      description: "Desc 2",
      date: "2 March 1994",
    },
    {
      title: "Title 1",
      description: "Desc 1",
      date: "1 March 1990",
    },
    {
      title: "Title 2",
      description: "Desc 2",
      date: "2 March 1994",
    },
    {
      title: "Title 1",
      description: "Desc 1",
      date: "1 March 1990",
    },
    {
      title: "Title 2",
      description: "Desc 2",
      date: "2 March 1994",
    },
    {
      title: "Title 1",
      description: "Desc 1",
      date: "1 March 1990",
    },
    {
      title: "Title 2",
      description: "Desc 2",
      date: "2 March 1994",
    },
    {
      title: "Title 1",
      description: "Desc 1",
      date: "1 March 1990",
    },
    {
      title: "Title 2",
      description: "Desc 2",
      date: "2 March 1994",
    },
  ];
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Mon <a href="https://nextjs.org">Parcours</a>
        </h1>
        <Timeline items= {timelineArray} />
       
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      {/* <Footer /> */}
    </div>
  );
}
