import React, { useEffect, useRef, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Header from "../components/Header";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faJsSquare,
  faReact,
  faNodeJs,
} from "@fortawesome/free-brands-svg-icons";
import indexGsapAnimations from "../utils/gsapAnimations/indexGsapAnimations";
import Link from "next/link";

export default function Home() {
  const logosRef = useRef(null);
  const welcome1Ref = useRef(null);
  const buttonRef = useRef(null);
  indexGsapAnimations().button(buttonRef.current);
  useEffect(() => {
    //Icons Timelines
    indexGsapAnimations().welcome1(welcome1Ref.current);
    if (logosRef.current) {
      indexGsapAnimations().logos(logosRef.current);
    }
    indexGsapAnimations().button(buttonRef.current);
    indexGsapAnimations().typingEffect();
  }, []);

  return (
    <div className="container">
      <Head>
        <title>WebNumerik - Développement Web React</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <div className={styles.welcome1} ref={welcome1Ref}>
          <section className={styles.video}>
          <video loop autoPlay muted>
              <source src="./Thunderstorm.mp4" type="video/mp4" />
              Your browser does not support the video tag.
            </video>
          </section>
          <h2 className={styles.description}>
            Je suis <span className={styles.myName}>Yves</span>
          </h2>
          <div className={styles.animation}>
            <div style={{ display: "flex", alignItems: "flex-end" }}>
              <h1 className={styles.title}>Développeur</h1>
              <div className={styles.icons}>
                <span className={styles.logoJs}>
                  <FontAwesomeIcon icon={faJsSquare} />
                </span>
              </div>
              <h2
                className={styles.title}
                style={{ position: "absolute", top: "95%", right: "0" }}
              >
                FullStack
              </h2>
            </div>
            <span
              id="reactText"
              className={`${styles.reactText} ${styles.title}`}
              style={{ color: "floralwhite" }}
            >
              RTCAE-ENTXSJ
            </span>
            <div
              className={styles.icons}
              ref={logosRef}
              style={{ position: "absolute" }}
            >
              <span className={styles.logoReact}>
                <FontAwesomeIcon icon={faReact} />
              </span>
              <span className={styles.logoNodeJs} style={{marginLeft:"1rem"}}>
                <FontAwesomeIcon icon={faNodeJs} />
              </span>
            </div>
          </div>

          <span className={styles.question}>UNE QUESTION ? UN BESOIN ?</span>
          <Link
            href="/contact"
          >
            <a>
              <button className={styles.buttonContact} ref={buttonRef}>
                CONTACTEZ-MOI
              </button>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
}
